# Generated by Django 5.0.1 on 2024-02-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='order_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
