# Generated by Django 5.0.1 on 2024-02-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='ran_figure',
            new_name='ran_quiz_num',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='ran_four',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='ran_movie',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='ran_music',
        ),
    ]
