# Generated by Django 5.0.1 on 2024-02-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0002_rename_ran_figure_gameroom_ran_quiz_num_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='ran_quiz_num',
            new_name='ran_figure',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='ran_four',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='ran_movie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='ran_music',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
