# Generated by Django 5.0.1 on 2024-02-06 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0002_gameroom_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='created_by',
        ),
    ]
