# Generated by Django 5.0.1 on 2024-03-08 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='order_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
