# Generated by Django 5.0.1 on 2024-02-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0002_alter_gameroom_room_name'),
        ('chattings', '0002_gameroom_order_num'),
    ]

    operations = [
    ]
