# Generated by Django 5.0.1 on 2024-02-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0003_remove_gameroom_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='participants',
            field=models.IntegerField(default=0),
        ),
    ]
