# Generated by Django 5.0.1 on 2024-02-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chattings', '0003_gameroom_ran_body'),
        ('chattings', '0003_gameroom_ran_mudo'),
    ]

    operations = [
    ]
