# Generated by Django 5.0.1 on 2024-02-07 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='노래제목')),
                ('music', models.TextField(verbose_name='노래 파일 경로')),
                ('singer', models.CharField(max_length=20, verbose_name='가수')),
                ('youtube', models.TextField(verbose_name='유튜브')),
            ],
        ),
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicGames.musicgame')),
            ],
        ),
    ]
