# Generated by Django 5.0.1 on 2024-01-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicGames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicgame',
            name='singer',
            field=models.CharField(default=1, max_length=20, verbose_name='가수'),
            preserve_default=False,
        ),
    ]
