# Generated by Django 5.0.1 on 2024-02-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicGames', '0002_musicgame_singer'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicgame',
            name='youtube',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
