# Generated by Django 5.0.1 on 2024-02-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicGames', '0003_musicgame_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicgame',
            name='youtube',
            field=models.TextField(verbose_name='유튜브'),
        ),
    ]
