# Generated by Django 5.0.1 on 2024-02-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieGames', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizList',
        ),
    ]
