# Generated by Django 5.0.1 on 2024-01-30 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieGames', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieGames.moviegame')),
            ],
        ),
    ]
