# Generated by Django 5.0.1 on 2024-02-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_path', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('figure_quiz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='figure.figure')),
            ],
        ),
    ]
