# Generated by Django 5.0.1 on 2024-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('figure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='image_path',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
