# Generated by Django 5.0.1 on 2024-02-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bodyGames', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bodygame_animal',
            old_name='animal',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='bodygame_food',
            old_name='food',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='bodygame_job',
            old_name='job',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='bodygame_proverb',
            old_name='proverb',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='bodygame_thing',
            old_name='thing',
            new_name='word',
        ),
    ]
